ecomapp/urls.py
from django.urls import path
from .views import *

app_name ="ecomapp"
urlpatterns = [
    path("",HomeView.as_view(), name="home"),
    path("login/",LoginView.as_view(), name="login"),
    path("register/",RegisterView.as_view(), name="register"),
    path("seller/",SellerView.as_view(), name="seller"),
    path("product/<slug:slug>/",ProductDetailView.as_view(),name="productdetail"),
    path("add-to-cart-<int:pro_id>/",AddToCartView.as_view(),name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    


   

]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
    path("shop/",include("ecomapp.urls"))
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Customer(models.Model):
  user = models.OneToOneField(User, on_delete=models.CASCADE)
  full_name = models.CharField(max_length=200)
  address = models.CharField(max_length=200, null=True, blank=True)
  joined_on = models.DateTimeField(auto_now_add=True)

  def _str_(self):
      return self.full_name


class Category(models.Model):
  title = models.CharField(max_length=200)
  slug = models.SlugField(unique=True)

  def _str_(self):
      return self.title

class Product(models.Model):
   title = models.CharField(max_length=200)
   slug = models.SlugField(unique=True)
   category = models.ForeignKey(Category, on_delete=models.CASCADE)
   image = models.ImageField(upload_to="products")
   marked_price = models.PositiveIntegerField()
   selling_price = models.PositiveIntegerField()
   description = models.TextField()
   return_policy  = models.CharField(max_length=300, null=True, blank=True)
   view_count = models.PositiveIntegerField(default=0)


def _str_(self):
   return self.title

class Cart(models.Model):
   customer = models.ForeignKey(
   Customer, on_delete=models.SET_NULL, null=True, blank=True)
   total = models.PositiveIntegerField(default=0)
   created_at = models.DateTimeField(auto_now_add=True)

def _str_(self):
    return "Cart: " + str(self.id)

class CartProduct(models.Model):
 cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
 product = models.ForeignKey(Product, on_delete=models.CASCADE)
 rate = models.PositiveIntegerField()
 quantity = models.PositiveIntegerField()
 subtotal = models.PositiveIntegerField()

def _str_(self):
    return "Cart: " + str(self.cart.id) + "CartProduct:" + str(self.id)

ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Cancelled", "Order Cancelled"),

)

class Order(models.Model):
   cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
   ordered_by = models.CharField(max_length=200)
   shipping_address = models.CharField(max_length=200)
   mobile = models.CharField(max_length=10)
   email = models.EmailField(null=True,blank=True)
   subtotal = models.PositiveIntegerField()
   discount = models.PositiveIntegerField()
   total = models.PositiveIntegerField()
   order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
   created_at = models.DateTimeField(auto_now_add=True)


def _str_(self):
    return "Order: " + str(self.id)

ecomapp/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import *

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_list'] = Product.objects.all()
        return context


class LoginView(TemplateView):
    template_name = "login.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['allcategories'] = Category.objects.all().order_by("-id")
        return context

class RegisterView(TemplateView):
    template_name = "register.html"

class SellerView(TemplateView):
    template_name = "seller.html"


class ProductDetailView(TemplateView):
    template_name = "productdetail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        url_slug = self.kwargs['slug']
        product = Product.objects.get(slug=url_slug)
        context['product'] = product
        return context


class AddToCartView(TemplateView):
    template_name = "addtocart.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_id = self.kwargs['pro_id']
        product_obj = Product.objects.get(id=product_id)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart_obj = Cart.objects.get(id=cart_id)
            this_product_in_cart = cart_obj.cartproduct_set.filter(
                product=product_obj)
            #item already exists in cart
            if this_product_in_cart.exists():
                cartproduct = this_product_in_cart.last()
                cartproduct.quantity += 1
                cartproduct.subtotal += product_obj.selling_price
                cartproduct.save()
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
            #new item is added in cart
            else:
                cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
                cart_obj.total += product_obj.selling_price
                cart_obj.save()
        else:
            cart_obj = Cart.objects.create(total=0)
            self.request.session['cart_id'] = cart_obj.id
            cartproduct = CartProduct.objects.create(
                    cart=cart_obj, product=product_obj, rate=product_obj.selling_price, quantity=1, subtotal=product_obj.selling_price)
            cart_obj.total += product_obj.selling_price
            cart_obj.save()

        return context

class MyCartView(TemplateView):
    template_name = "mycart.html"
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_id = self.request.session.get("cart_id", None)
        if cart_id:
            cart = Cart.objects.get(id=cart_id)
        else:
            cart = None
        context['cart'] = cart
        return context

templates/addtocart.html
{% extends 'base.html' %} 

{% block title %}Add To Cart{% endblock %} 

{% block content %} 
<div class="container">
    <h3>Product added to cart successfully</h3>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{%static 'css/main.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">   
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <img src = "static/images/logo.png" style="height: 65px;" class="d-block w-90" alt="image">
    <nav class="navbar navbar-light bg-light">
        <form class="form-inline">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </nav>        

				</form>
			</div>
        </div>
    </nav>
  
    
</head>
<body>
        
                <ul>
                   <li><a href="{% url 'ecomapp:seller' %}">Seller</a></li>
                   <li><a href="{% url 'ecomapp:register' %}">Register</a></li>
                   <li><a href="{% url 'ecomapp:login' %}">Login</a></li>
                   <li><a href="{% url 'ecomapp:mycart' %}"><i class="fa-solid fa-cart-shopping"style="font-size:20px;"></i></a></li>
                   

                   
                </ul> 
                
            <hr>
                
    {% block content %}
    {% endblock %}
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <img src="{% static'images/12.jpg}" alt="Los Angeles">
    </div>

    <div class="item">
      <img src="{% static'images/13.jpg}" alt="Chicago">
    </div>

    <div class="item">
      <img src="{% static'images/12.jpg}" alt="New York">
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>


{% endblock %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %}My Cart{% endblock %} 

{% block content %} 
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h4>Items in my Cart</h4><hr>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartProduct_set.all %} 
                    <tr> 
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %} 

templates/productdetail.html
{% extends 'base.html' %} 

{% block title %}{{product.title}}{% endblock %} 

{% block content %} 
<div class="container">
    <h3>Product:{{product.title}}</h3><hr>
    <div class="row">
        <div class="col-md-6">
            <img src="{{product.image.url}}" alt="" class="img-fluid">
        </div>
        <div class="col-md-6">
            <h4>{{product.title}}</h4>
            <h5>Category: {{product.category}}</h5>
            <h5>Price: <strike>Rs.{{product.marked_price}}</strike>Rs.{{product.selling_price}}</h5>
            <p>{{product.description}}</p>
            <hr>
            <p class="text-info">Return Policy:{{product.return_policy}}</p>
            <a href="{% url 'ecomapp:addtocart' product.id %}" class="btn btn-info">Add To Cart</a>
        </div>
    </div>
</div>
{% endblock %}

templates/shop.html
{% extends 'base.html' %} 

{% block title %}Shop{% endblock %} 

{% block content %} 
<div class="container">
   <h1 class="text-center" >shop site</h1>
   <div class="row"></div>
   {% for cat in allcategories %} 
     <h4>{{cat.title}}</h4><hr>
    <div class="row mt-3">

       {% for p in cat.product_set.all %} 
         <div class="col-md-3">
           <div class="m-4">
              <h4><a href="{% url 'ecomapp:productdetail' p.slug %}">{{p.title}}</a></h4>
              <img src="{{p.image.url}}" alt="" class="img-fluid" style="height:2500; object-fit:cover;">
              <p class="mt-3">Price:<strike>Rs.{{p.marked_price}}</strike>Rs.{{p.selling_price}}</p>
              <a href="{% url 'ecomapp:addtocart' p.id %}" class="btn btn-primary">Add To Cart</a>
            </div>
         </div>
      {% endfor %} 
     </div>
   {% endfor %}
   </div>
</div>
{% endblock %} 

templates/slider.html
{% load static %} 
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
  
    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="{% static'images/12.jpg}" alt="Los Angeles">
      </div>
  
      <div class="item">
        <img src="{% static'images/13.jpg}" alt="Chicago">
      </div>
  
      <div class="item">
        <img src="{% static'images/12.jpg}" alt="New York">
      </div>
    </div>
  
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
{% endblock %}